services:
  - type: web
    name: yugen-talk-backend
    env: java
    region: oregon
    plan: free
    buildCommand: ./mvnw clean package 
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
    buildEnvVars:
      - key: JAVA_VERSION
        value: 17
