services:
  - type: web
    name: yugen-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/chatbackend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
    build:
      env:
        JAVA_HOME: /opt/render/project/.java
        JAVA_VERSION: 17

